# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Rekrutacja w Mechaniku
name: Zespół Szkół nr 1
subname: im. gen. José de San Martin
address1: ul. Armii Krajowej 10
address2: 09-200 Sierpc
phone: (24) 275 23 73
phone2: (24) 275 34 21
email: zs1sierpc@op.pl
language: pl
charset: UTF-8
description: >- # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "/rekrutacja" # the subpath of your site, e.g. /blog
url: "http://zs1sierpc.cba.pl" # the base hostname & protocol for your site, e.g. http://example.com
facebook_username: ZespolSzkolNr1WSierpcu
youtube_username: mechaniksierpc
main_site: "http://zs1sierpc.cba.pl"

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed

collections:
  technikum:
    output: true
    permalink: /technikum/:slug/
  liceum:
    output: true
    permalink: /liceum/:slug/

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
